# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

Dotenv.load('.env')

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # App Store Connect API setup
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )
    
    increment_build_number(xcodeproj: "zotik.xcodeproj")
    build_app(workspace: "zotik.xcworkspace", scheme: "zotik")
    upload_to_testflight
  end
end
